#pragma once

#include <algorithm>
#include <any>
#include <atomic>
#include <bit>
#include <bitset>
#include <cassert>
#include <chrono>
#include <cmath>
#include <codecvt>
#include <condition_variable>
#include <cstddef>
#include <cstring>
#include <cstdint>
#include <deque>
#include <filesystem>
#include <format>
#include <forward_list>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <list>
#include <locale>
#include <map>
#include <memory>
#include <memory_resource>
#include <mutex>
#include <new>
#include <optional>
#include <ostream>
#include <random>
#include <ranges>
#include <regex>
#include <set>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <typeindex>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>
#include <version>